version: '3.4'

services:
  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: src/Services/Identity/IdentityServer/Dockerfile
    networks:
      - betterttd

  openttd.api:
    image: ${DOCKER_REGISTRY-}openttdapi
    build:
      context: .
      dockerfile: src/Services/OpenTTD/OpenTTD.API/Dockerfile
    networks:
      - betterttd

networks:
  betterttd:
    name: betterttd.network