version: '3.4'

services:
  identityserver:
    image: identityserver
    container_name: identityserver
    build:
      context: .
      dockerfile: src/Services/Identity/IdentityServer/Dockerfile
    networks:
      - betterttd

  identityserver.db:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: identityserver.db
    networks:
      - betterttd

  openttd.api:
    image: openttd.api
    container_name: openttd.api
    build:
      context: .
      dockerfile: src/Services/OpenTTD/OpenTTD.API/Dockerfile
    networks:
      - betterttd

networks:
  betterttd:
    name: betterttd.network